services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_files:/app/staticfiles
    depends_on:
      - db

volumes:
  postgres_data:
  static_files:
