# Generated by Django 5.2.8 on 2025-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
